USE [master]
GO

/****** Object:  Database [MatematikApp]    Script Date: 05.12.2019 13:31:21 ******/
CREATE DATABASE [MatematikApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MatematikApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MatematikApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MatematikApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MatematikApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MatematikApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MatematikApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MatematikApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MatematikApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MatematikApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MatematikApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [MatematikApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MatematikApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MatematikApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MatematikApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MatematikApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MatematikApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MatematikApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MatematikApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MatematikApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MatematikApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MatematikApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MatematikApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MatematikApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MatematikApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MatematikApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MatematikApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MatematikApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MatematikApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MatematikApp] SET  MULTI_USER 
GO

ALTER DATABASE [MatematikApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MatematikApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MatematikApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MatematikApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MatematikApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MatematikApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MatematikApp] SET  READ_WRITE 
GO


